name: Flask2Docker2Github2CloudRun
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0 ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run Tests
        run: |
          python pytest ./testFlask.py  --cov=./
